---
include:
  - project: 'metastake/skeleton-pipeline'
    ref: v1.1.1
    file: '/docker.yml'
  - project: 'metastake/skeleton-pipeline'
    ref: v1.1.1
    file: '/security.yml'

variables:
  TAG: $CI_COMMIT_TAG

dockerize:
  only:
    - tags
