---
include:
  - project: 'metastake/skeleton-pipeline'
    ref: v1.1.1
    file: '/docker.yml'
  - project: 'metastake/skeleton-pipeline'
    ref: v1.1.1
    file: '/security.yml'

stages:
  - publish
  - security

variables:
  TAG: $CI_COMMIT_TAG

dockerize:
  only:
    - tags

container_scanning:
  rules:
    - if: $CI_COMMIT_TAG
