---
include:
  - project: 'metastake/skeleton-pipeline'
    ref: v1.1.1
    file: '/docker.yml'
  - project: 'metastake/skeleton-pipeline'
    ref: v1.1.1
    file: '/security.yml'

variables:
  DOCKER_IMAGE: ${DOCKER_USERNAME}/${CI_PROJECT_NAME}:${CI_COMMIT_TAG}
  DOCKER_BUILD_ARGS: ""

stages:
  - publish
  - security

dockerize:
  only:
    - tags

container_scanning:
  rules:
    - if: $CI_COMMIT_TAG
